# Generated by Django 2.1.3 on 2018-11-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(default='', max_length=500)),
                ('normal_url', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('resolved_url', models.URLField(blank=True, default='', null=True)),
                ('date_saved', models.TextField(blank=True, default='', null=True)),
                ('date_published', models.TextField(blank=True, default='', null=True)),
                ('excerpt', models.TextField(blank=True, default='', null=True)),
                ('cover_image', models.TextField(blank=True, default='', null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
