# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Anywhere Reader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Anywhere Reader
  pod 'Kingfisher', '~> 4.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
end
